services:
  web:
    build: .
    ports: 
      - 8000:8000
    volumes:
      - .:/app
    networks:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:14.6
    networks:
      - db
    env_file:
      - env
    # environment:
    #   - POSTGRES_DB=${DB_NAME}
    #   - POSTGRES_USER$={DB_USER}
    #   - POSTGRES_PASSWORD=${DB_PASSWORD}
    #   - POSTGRES_PORT=${DB_PORT}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - 5432:5432

networks:
  db:
    driver: bridge