services:
  web:
    build: .
    ports: 
      - 8000:8000
    volumes:
      - .:/app
    networks:
      - db
    # env_file:
    #   - .env
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASSWORD}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:14.6
    networks:
      - db
    volumes:
      - psql_db:/var/lib/postgresql
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - 5432:5432

volumes:
    psql_db:
      driver: local

networks:
  db:
    driver: bridge