services:
  web:
    build: .
    ports: 
      - 8000:8000
    environment:
      DB_HOST: "test-db.crrrcloqjh9n.us-east-1.rds.amazonaws.com"
      DB_NAME: "test-db"
      DB_USER: "postgres"
      DB_PASS: "postgres"
      DJANGO_SECRET_KEY: "changeme"

    depends_on:
      - db

  db:
    image: postgres:14.6
    environment:
      - POSTGRES_DB="test-db"
      - POSTGRES_USER="postgres"
      - POSTGRES_PASSWORD="postgres"
      - POSTGRES_HOST="test-db.crrrcloqjh9n.us-east-1.rds.amazonaws.com"
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432