apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        resources:
          limits:
            memory: "1Gi"
            cpu: 1
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: secrets
              key: db-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets 
              key: db-password
        - name: POSTGRES_DB
          value: $(DB_NAME)
          # valueFrom:
          #   configMapKeyRef:
          #     name: postgres-config
          #     key: db-name
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432


