# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: postgres-deployment
#   labels:
#     app: postgres
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: postgres
#   template:
#     metadata:
#       labels:
#         app: postgres
#     spec:
#       containers:
#       - name: postgres
#         image: postgres
#         env:
#         - name: POSTGRES_USER
#           valueFrom:
#             secretKeyRef:
#               name: secrets
#               key: db-user
#         - name: POSTGRES_PASSWORD
#           valueFrom:
#             secretKeyRef:
#               name: secrets 
#               key: db-password
#         - name: POSTGRES_DB
#           valueFrom:
#             configMapKeyRef:
#               name: postgres-config
#               key: db-name
#         ports:
#         - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: ExternalName
  externalName: group7-rds-db.crrrcloqjh9n.us-east-1.rds.amazonaws.com


