---
- hosts: "master"
  become: true
  tasks:
  - name: Assign elements of the list to variables dynamically
    vars:
      mylist: [1,2,3]
    set_fact:
      "variable{{ my_idx }}": "{{ item }}"
    loop: "{{ mylist }}"
    loop_control:
      index_var: my_idx
    # - name: Create join node command
    #   shell: /snap/bin/microk8s add-node
    #   register: join_tokens
    #   ignore_errors: true
    #   loop: "{{ range(1, num_iterations|int + 1) | list }}"
    #   vars:
    #     num_iterations: 3

    # - name: Set facts for each join token
    #   set_fact:
    #     microk8s_join_{{ loop.index }}: "{{ item.stdout_lines[4] }}"
    #   loops: "{{ join_tokens.results }}"
    #   debug:
    #     var: microk8s_join_{{ loop.index }}
  
