---
- name: Update servers
  hosts: master
  become: true
  vars:
    numbers: [1,2,3]

  tasks:
  - name: Update web servers
    with_items: "{{ numbers }}"
    set_fact:
      "variable_{{ item }}": "{{ item }}"

  - debug:
      msg: "variable_{{ item }}"
    with_items: "{{ numbers }}"
