---
- name: Update servers
  hosts: kubenodes
  become: true

  tasks:
  - name: Update web servers
    apt:
      upgrade: yes
      update_cache: yes

  - name: Install snap package installer
    apt:
      name: snapd
      state: present

  - name: Instal Microk8s
    snap:
      name: microk8s
      classic: true

  - name: Add current user to microk8s group
    shell:
      cmd: "sudo usermod -a -G microk8s {{ ansible_user }}"

  - name: Create join node command
    command: microk8s add-node
    delegate_to: "{{ groups['master'][0] }}"
    register: token
    ignore_errors: true
    when: "'master' in group_names"

  - set_fact:
      microk8s-join: "{{ token..stdout }}"
    when: "'master' in group_names"

  - debug:
      var: microk8s_join
    when: "'master' in group_names"
