---
- name: Update servers
  hosts: master
  become: true
  vars:
    numbers: [1,2,3]

  tasks:
  - name: worker count
    set_fact:
      workers_count: "{{ groups.workers | length }}"

  - debug:
      msg: "{{ workers_count }}"

  - name: Create join node command
    shell: /snap/bin/microk8s add-node
    register: join_token
    ignore_errors: true
    loop: "{{ range(1, num_iterations|int + 1 ) | list }}"
    vars:
      num_iterations: "{{ workers_count }}"

  - set_fact:
      microk8s_join_list: "{{ microk8s_join_list | default([]) + ['/snap/bin/' + item.stdout_lines[4]] }}"
    loop: "{{ join_token.results }}"
    loop_control:
      index_var: my_idx


  # - debug:
  #     msg: "{{ microk8s_join_list }}"

  - name: Run command on worker nodes
    loop: "{{ microk8s_join_list }}"
    loop_control:
      index_var: my_idx
    debug: 
      msg: "{{ item[my_idx] }}"

